180725

diff --git a/demux-run-10x b/demux-run-10x
--- a/demux-run-10x
+++ b/demux-run-10x
@@ -17,23 +17,18 @@
 
 #Constants
 OUTPUT_PARENT="/gale/netapp/seq2/illumina_runs"
-SAMPLESHEET_PARENT="/gale/netapp/seq2/illumina_runs/.samplesheets"
+SAMPLESHEET_PATH="/gale/netapp/seq2/illumina_runs/.samplesheets"
 LOG_PARENT="/gale/netapp/seq2/illumina_runs/.demux_logs"
 QSUB_PARENT="/gale/netapp/seq2/illumina_runs/.qsub"
-RTA_COMPLETE="RTAComplete.txt"
 
-timestamp="$(date "+%y%m%d%H%M%S")"
 run_path="$(pwd)"
 run_name="$(basename $run_path)"
-run_name_ts="${run_name}_$timestamp"
-output_path="$OUTPUT_PARENT/$run_name_ts"
 log_name="$run_name_ts.txt"
 log_path="$LOG_PARENT/$log_name"
 
 usage() {
-echo "Usage: demux-commandline -s SampleSheet.csv -m n"
-echo "-s, samplesheet filename in default samplesheets directory: /gale/netapp/seq2/illumina_runs/.samplesheets"
-echo "-O, additional bcl2fastq options enclosed in quotes"
+echo "eg, demux-run -s /gale/netapp/seq2/illumina_runs/.samplesheets/180709_K00161_0224_AHVMNJBBXX/SampleSheet_180709_K00161_0224.csv"
+echo "-s, path to samplesheet file"
 echo "-h, this help message"
 }
 
@@ -47,32 +42,51 @@ while getopts ":s:O:h" opt; do
       ;;
     h) 
       usage
-      exit
+      exit 1
       ;;
     \?)
       echo "Invalid option: -$OPTARG"
       usage
-      exit
+      exit 1
       ;;
   esac
 done
 
-if [ ! -f "$run_path/$RTA_COMPLETE" ] ; then
-  echo "This does not appear to be a valid run directory!"
+echo "bclopts: $bclopts"
+
+bcl2fastq_command_line=$(demux-commandline-10x -s "$SAMPLESHEET_PATH" -O "$bclopts")
+
+#check demux-commandline script exit status
+if [ $(echo $?) -eq 1 ] ; then
+  echo "$bcl2fastq_command_line"
   exit 1
 fi
 
-if [ ! -f $samplesheet ]; then
-  echo "Error! $samplesheet not found!"
-  exit 1
-fi
+#extract info from command line for qsub
 
-bcl2fastq_command_line="nohup bcl2fastq \
-  -R $run_path \
-  --sample-sheet $SAMPLESHEET_PATH \
-  -o $output_path \
-  $bclopts \
-  &> $log_path"
+#run number
+qsub_dir=$(echo $bcl2fastq_command_line \
+  | awk -F"/" '{print $NF}' \
+  | awk -F"_" '{print "d"$3"_"}')
 
+#run number + timestamp
+qsub_dir+=$(echo $bcl2fastq_command_line \
+  | awk -F"/" '{print $NF}' \
+  | awk -F"_" '{print substr($NF,3,8)}')
+
+qsub_path="$QSUB_PARENT/$qsub_dir"
+
+mkdir $qsub_path
+
+echo $bcl2fastq_command_line > $qsub_path/commands
+
+cd $qsub_path
+
+echo "Submitting job to queue"
+2q
+
+node=$(qstat | grep "${qsub_dir:0:10}")
+
+echo "$node" > $qsub_path/node.txt
 echo $bcl2fastq_command_line
-exit 0
+echo "$qsub_path"
